-- Створення таблиці USERS
CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(100) NOT NULL CHECK (EMAIL REGEXP '^[^@]+@[^@]+\\.[^@]+$'),
    NAME VARCHAR(50) NOT NULL CHECK (CHAR_LENGTH(NAME) BETWEEN 2 AND 50),
    IS_AUTHORIZED BOOLEAN NOT NULL
);

-- Створення таблиці REGULAR_USERS
CREATE TABLE REGULAR_USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT,
    WEEKLY_SESSION_COUNT INT CHECK (WEEKLY_SESSION_COUNT BETWEEN 0 AND 10),
    MONTHLY_INVITE_COUNT INT CHECK (MONTHLY_INVITE_COUNT BETWEEN 0 AND 20),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Створення таблиці INVITED_USERS
CREATE TABLE INVITED_USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT,
    INVITATION_STATUS ENUM('pending', 'accepted', 'rejected') NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Створення таблиці MUSIC_SESSIONS
CREATE TABLE MUSIC_SESSIONS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CREATED_AT DATETIME NOT NULL CHECK (CREATED_AT > NOW()),
    MAX_PARTICIPANTS INT CHECK (MAX_PARTICIPANTS BETWEEN 1 AND 6),
    STATUS ENUM('active', 'ended', 'paused') NOT NULL
);

-- Створення таблиці PLAYLISTS
CREATE TABLE PLAYLISTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL CHECK (CHAR_LENGTH(NAME) BETWEEN 1 AND 100),
    DESCRIPTION VARCHAR(500) CHECK (CHAR_LENGTH(DESCRIPTION) BETWEEN 0 AND 500)
);

-- Створення таблиці TRACKS
CREATE TABLE TRACKS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(200) NOT NULL CHECK (CHAR_LENGTH(TITLE) BETWEEN 1 AND 200),
    DURATION INT CHECK (DURATION > 0)
);

-- Створення таблиці INVITATIONS
CREATE TABLE INVITATIONS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    RECIPIENT_EMAIL VARCHAR(100) NOT NULL CHECK (RECIPIENT_EMAIL REGEXP '^[^@]+@[^@]+\\.[^@]+$'),
    STATUS ENUM('sent', 'delivered', 'accepted', 'rejected') NOT NULL,
    SENT_AT DATETIME NOT NULL CHECK (SENT_AT <= NOW())
);
