name: Print Software Versions

on: [push]

jobs:
  data-processing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print Node.js version
      run: node -v

    - name: Print Express.js version
      run: npm list express

  data-access:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print MongoDB version
      run: mongo --version
